name: Build_ESP32S3

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32@2.0.17 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Download & Fix Libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          git clone https://github.com/me-no-dev/ESPAsyncWebServer.git $HOME/Arduino/libraries/ESPAsyncWebServer
          git clone https://github.com/me-no-dev/AsyncTCP.git $HOME/Arduino/libraries/AsyncTCP
          
          # --- TRIK SAKTI FIX MD5 ---
          # Kita ganti paksa tulisan #include "md5.h" jadi #include "rom/md5_utils.h"
          # di dalem file WebAuthentication.cpp biar gak error
          sed -i 's/#include "md5.h"/#include "rom\/md5_utils.h"/' $HOME/Arduino/libraries/ESPAsyncWebServer/src/WebAuthentication.cpp

            - name: Compile Sketch
        run: |
          mkdir -p build
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --output-dir ./build --library $HOME/Arduino/libraries *.ino

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32S3-Firmware
          path: build/*.bin
          
