name: Build_ESP32S3

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32@2.0.17 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Specific Libraries
        run: |
          # Pakai versi 1.2.3 karena ini yang paling stabil buat masalah md5.h
          arduino-cli lib install "ESPAsyncWebServer@1.2.3"
          arduino-cli lib install "AsyncTCP"

      - name: Compile Sketch
        run: |
          # Mencari file .ino secara otomatis di root folder
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --libraries ./libraries *.ino
